name: fittrix_application
description: Fittrix application assignment for interview
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  cached_network_image: ^3.2.3
  dio: ^5.2.1+1
  video_player: ^2.6.1
  flutter_secure_storage: ^8.0.0
  intl: ^0.18.1
  logger: ^1.4.0
  pretty_dio_logger: ^1.3.1

  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.6

flutter:
  uses-material-design: true
  assets:
    - assets/videos/
